import { NextPage } from 'next/types';
import Head from 'next/head';
import ComponentsProfile from '../components/Profile';
import styles from '../styles/Home.module.css';
import Data from '../data/timeTracker.json';
import styled from '@emotion/styled';
import Card from '../components/Card';

const GridContainerStyled = styled('div')`
  display: grid;
  grid-template-columns: 1fr;
  gap: 2em;
  grid-template-areas:
    'Profile'
    '.';

  @media screen and (min-width: 640px) {
    grid-template-columns: repeat(2, 1fr);
    gap: 2em;
    grid-template-areas: 'Profile Profile' '. .';
  }

  @media screen and (min-width: 1008px) {
    grid-template-columns: repeat(4, 1fr);
    grid-template-rows: repeat(2, 1fr);
    gap: 2em;
    grid-template-areas:
      'Profile . . .'
      'Profile . . .';
  }
`;

const Home: NextPage = () => {
  const {
    timeTracker: {
      user: { firstName, lastName },
      cards,
    },
  } = Data;
  return (
    <div className={styles.container}>
      <Head>
        <title>Time Tracker</title>
        <meta
          name="Frontend Mentor challenge"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        {/* eslint-disable-next-line @next/next/no-page-custom-font */}
        <link
          href="https://fonts.googleapis.com/css2?family=Rubik:wght@300;400;500&display=swap"
          rel="stylesheet"
        />
      </Head>

      <main className={styles.main}>
        <GridContainerStyled>
          <>
            <ComponentsProfile firstName={firstName} lastName={lastName} />
            {cards?.map((card, index) => (
              <Card {...card} key={index} />
            ))}
          </>
        </GridContainerStyled>
      </main>
    </div>
  );
};

export default Home;
